/*CREATE DATABASE MYDB
COLLATE UTF8_GENERAL_CI;
*/

CREATE TABLE Customer(
	ID VARCHAR(20) NOT NULL,
	PWD VARCHAR(20) NOT NULL,
	PHONE_NUM VARCHAR(30) NULL,
	ADDRESS VARCHAR(60) NULL
	);

CREATE TABLE Store_OWNER(
	STORE_OWN_ID VARCHAR(20) PRIMARY KEY,
	STORE_OWN_PWD VARCHAR(20) NOT NULL
	);

CREATE TABLE Store(
	STORE_ID VARCHAR(20) PRIMARY KEY,
	STORE_ADD VARCHAR(20) NOT NULL,
	STORE_NUM VARCHAR(20) NULL,
	STORE_OWN_ID VARCHAR(20),
	FOREIGN KEY (STORE_OWN_ID) REFERENCES Store_OWNER (STORE_OWN_ID)
	);
	
CREATE TABLE MENU(
	STORE_ID VARCHAR(20),
	FOOD_NAME VARCHAR(20) NOT NULL,
	PRICE VARCHAR(10) NOT NULL,
	FOREIGN KEY (STORE_ID) REFERENCES Store (STORE_ID)
	);
	
CREATE TABLE ADMIN(
	ADMIN_ID VARCHAR(20) PRIMARY KEY,
	ADMIN_PWD VARCHAR(20) NOT NULL
	);

CREATE TABLE FESTIVAL(
	FESTIVAL_NAME VARCHAR(20) PRIMARY KEY,
	FESTIVAL_START VARCHAR(10),
	FESTIVAL_END VARCHAR(10),
	FESTIVAL_ADD VARCHAR(20)
	);
